receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  googlecloud:
    log:
      default_log_name: otlp.xtc.xceptance.com
      resource_filters:
       - prefix: xtc.

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, googlecloud]
      #~ exporters: [debug]
