# Site settings
title: XLT Docs
description: Xceptance LoadTest - XLT, Documentation, Manual, Howto, FAQ
timezone: UTC

# Build settings
markdown: kramdown
plugins: [jekyll-textile-converter]

# Do not copy the drafts
exclude: [_drafts]

topics:
    getting-started: "Getting Started"
    how-to: "How-To"
    user-manual: "User Manual"
    release-notes: "Release Notes"
