###############################################################################
# 
# General agent controller settings.
#
###############################################################################

## The host (host name or IP address) to which the agent controller is bound. 
## This way, you can force the agent controller to listen on a specific network
## interface. If not configured, the controller will listen on all available
## network interfaces.
#com.xceptance.xlt.agentcontroller.host = 

## The HTTPS port the agent controller listens at.
com.xceptance.xlt.agentcontroller.port = 8500

## The password that a remote master controller must provide to enable it to  
## communicate with the agent controller. If empty or commented out, no 
## authentication will be enforced. Change the default value immediately.
com.xceptance.xlt.agentcontroller.password = xceptance

## The password the certificate key store is encrypted with.
com.xceptance.xlt.agentcontroller.keystore.password = topsecret

## The password the certificate is encrypted with.
com.xceptance.xlt.agentcontroller.keystore.key.password = topsecret

## The directory where the separate agent directories are located.
## Defaults to: <XLT_HOME>/agent
#com.xceptance.xlt.agentcontroller.agentsdir = agent

## The directory where the temp files are located.
## Defaults to: system specific value of property 'java.io.tmpdir'
#com.xceptance.xlt.agentcontroller.tempdir =


###############################################################################
# 
# Private Machine Mode
#
# Use this mode if this Agent Controller runs on a private machine that is not 
# reachable from the Internet. Works only with XTC.
#
###############################################################################

## Whether the private machine mode is enabled (default: false).
com.xceptance.xlt.agentcontroller.privateMachine.enabled = true

## The name of the private machine (default: an artificial name). 
## Valid names must be between 1-63 characters long, contain only alphanumeric
## characters or hyphens, and cannot start or end with a hyphen.
#com.xceptance.xlt.agentcontroller.privateMachine.name = 

## Additional information about the private machine (default: empty).
#com.xceptance.xlt.agentcontroller.privateMachine.description = 

## The type of the private machine in terms of size 
## (one of TINY/SMALL/MEDIUM/LARGE; default: MEDIUM).
#com.xceptance.xlt.agentcontroller.privateMachine.type = MEDIUM

## The XTC host name and port (default: "xtc.xceptance.com" and 443).
#com.xceptance.xlt.agentcontroller.privateMachine.xtc.host = xtc.xceptance.com
#com.xceptance.xlt.agentcontroller.privateMachine.xtc.port = 443

## The XLT Relay host name and port (default: "xlt-relay.xceptance.com" and 443).
#com.xceptance.xlt.agentcontroller.privateMachine.xtc.relayHost = xlt-relay.xceptance.com
#com.xceptance.xlt.agentcontroller.privateMachine.xtc.relayPort = 443

## Client ID and secret to use when communicating with the XTC REST API
## (required, no defaults).
com.xceptance.xlt.agentcontroller.privateMachine.xtc.clientId =  
com.xceptance.xlt.agentcontroller.privateMachine.xtc.clientSecret = 

## The org and project short names in XTC (required, no defaults).
com.xceptance.xlt.agentcontroller.privateMachine.xtc.org = 
com.xceptance.xlt.agentcontroller.privateMachine.xtc.project = 


###############################################################################
#
# Log system configuration.
#
###############################################################################

rootLogger.appenderRef.console.ref = Console
rootLogger.appenderRef.file.ref = File
rootLogger.level = debug

appender.console.name = Console
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{HH:mm:ss,SSS}] %-5p [%t] - %m%n

appender.file.name = File
appender.file.type = RollingFile
appender.file.fileName = ${sys:com.xceptance.xlt.home}/log/agentcontroller.log
appender.file.filePattern = ${sys:com.xceptance.xlt.home}/log/agentcontroller-%i.log
appender.file.policies.type = Policies
appender.file.policies.size.type = SizeBasedTriggeringPolicy
appender.file.policies.size.size = 10MB
appender.file.strategy.type = DefaultRolloverStrategy
appender.file.strategy.max = 9
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%d{yyyy/MM/dd-HH:mm:ss,SSS}] %-5p [%t] %c - %m%n
