###############################################################################
# 
# General GCE Admin settings
#
###############################################################################

## The ID of your Google Cloud Platform project [required].
xlt.gce.projectId = 

## The maximum time [s] to wait for instances to reach the running state.
## Defaults to 300 seconds.
#xlt.gce.instanceConnectTimeout = 300
