###############################################################################
#
# Report Generator Logging Configuration
#
###############################################################################

rootLogger.appenderRef.file.ref = File
rootLogger.appenderRef.console.ref = Console
rootLogger.level = warn

logger.report-runtime.name = report
logger.report-runtime.level = info

appender.console.name = Console
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %m%n

appender.file.name = File
appender.file.type = RollingFile
appender.file.fileName = ${sys:com.xceptance.xlt.home}/log/reportgenerator.log
appender.file.filePattern = ${sys:com.xceptance.xlt.home}/log/reportgenerator-%i.log
appender.file.policies.type = Policies
appender.file.policies.size.type = SizeBasedTriggeringPolicy
appender.file.policies.size.size = 10MB
appender.file.strategy.type = DefaultRolloverStrategy
appender.file.strategy.max = 9
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%d{yyyy/MM/dd-HH:mm:ss,SSS}] %-5p [%t] %c - %m%n
