/*
 * Copyright (c) 2005-2026 Xceptance Software Technologies GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.xceptance.xlt.report;

import java.util.List;
import java.util.Map.Entry;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.vfs2.FileObject;

import com.xceptance.common.util.ByteCsvDecoder;

import com.xceptance.xlt.api.engine.ActionData;
import com.xceptance.xlt.api.engine.CustomData;
import com.xceptance.xlt.api.engine.CustomValue;
import com.xceptance.xlt.api.engine.Data;
import com.xceptance.xlt.api.engine.EventData;
import com.xceptance.xlt.api.engine.PageLoadTimingData;
import com.xceptance.xlt.api.engine.RequestData;
import com.xceptance.xlt.api.engine.TransactionData;
import com.xceptance.xlt.api.engine.WebVitalData;
import com.xceptance.xlt.agent.JvmResourceUsageData;
import com.xceptance.xlt.api.report.PostProcessedDataContainer;
import com.xceptance.common.util.CsvByteRow;

import com.xceptance.xlt.report.mergerules.MergeRule;
import com.xceptance.xlt.report.mergerules.MergeRuleProcessor;


/**
 * Parses lines to data records and performs any data record preprocessing that can 
 * be done in parallel. Preprocessing also includes executing request merge rules.
 */
class DataParserThread implements Runnable
{
    /**
     * Class logger.
     */
    private static final Log LOG = LogFactory.getLog(DataParserThread.class);

    /**
     * Pattern used to rename the name of Web driver timers generated by FF add-on.
     */
    private static final Pattern WD_TIMER_NAME_PATTERN = Pattern.compile("page_\\d+");

    /**
     * The data record factory.
     */
    private final DataRecordFactory dataRecordFactory;

    /**
     * The dispatcher that coordinates result processing.
     */
    private final Dispatcher dispatcher;

    /**
     * The start time of the report period. Data records generated outside this window will be ignored.
     */
    private final long fromTime;

    /**
     * The end time of the report period. Data records generated outside this window will be ignored.
     */
    private final long toTime;

    /**
     * The general config of the report generator
     */
    private final ReportGeneratorConfiguration config;

    /**
     * The request processing rules for this thread. Each parser thread gets its own copy of the rule set. This way,
     * there is no shared state between threads, hence we can more efficiently cache and process stuff.
     */
    private final List<MergeRule> mergeRules;

    /**
     * Constructor.
     *
     * @param dispatcher
     *            the dispatcher that coordinates result processing
     * @param dataRecordFactory
     *            the data record factory
     * @param fromTime
     *            the start time
     * @param toTime
     *            the end time
     * @param config
     *            the report generator settings
     */
    public DataParserThread(final Dispatcher dispatcher, final DataRecordFactory dataRecordFactory, 
                            final long fromTime, final long toTime,
                            final ReportGeneratorConfiguration config)
    {
        this.dataRecordFactory = dataRecordFactory;
        this.fromTime = fromTime;
        this.toTime = toTime;
        this.dispatcher = dispatcher;
        this.config = config;

        // Get the rules now! 
        // Reason: If a rule is invalid, an exception is thrown from here, which will terminate the report generator correctly.
        mergeRules = config.getMergeRules();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void run()
    {


        // single reused flyweight zero-copy row
        final CsvByteRow byteRow = new CsvByteRow();

        // our request processing, this is move away from here to test it better
        final MergeRuleProcessor requestProcessing = new MergeRuleProcessor(mergeRules,
                                                                          config.getRemoveIndexesFromRequestNames());

        final PostProcessedDataContainer postProcessedData = new PostProcessedDataContainer(10000);

        while (true)
        {
            postProcessedData.clear();
            try
            {
                // get a chunk of lines
                final DataChunk chunk = dispatcher.retrieveReadData();

                final String agentName = chunk.getAgentName();
                final String testCaseName = chunk.getTestCaseName();
                final String userNumber = chunk.getUserNumber();
                final boolean collectActionNames = chunk.getCollectActionNames();
                final boolean adjustTimerName = chunk.getAdjustTimerNames();
                final FileObject file = chunk.getFile();

                final long _fromTime = fromTime;
                final long _toTime = toTime;

                final List<byte[]> byteLines = chunk.getByteLines();
                final int size = byteLines.size();

                // parse the chunk of lines and preprocess the results

                int lineNumber = chunk.getBaseLineNumber();

                for (int i = 0; i < size; i++)
                {
                    Data data = null;

                    try
                    {
                        final byte[] rawLine = byteLines.get(i);
                        ByteCsvDecoder.parse(byteRow, rawLine);
                            
                        // get us the minimal data aka type and time
                        data = dataRecordFactory.createStatistics(byteRow.charAt(0, 0));
                        data.setBaseValues(byteRow);

                        // see if we have to keep it
                        final long time = data.getTime();
                        if (time < _fromTime || time > _toTime)
                        {
                            // nope
                            continue;
                        }

                        // finish parsing
                        data.setRemainingValues(byteRow);
                    }
                    catch (final Exception ex)
                    {
                        final String lineContent = new String(byteLines.get(i), java.nio.charset.StandardCharsets.UTF_8);
                        final String msg = String.format("Failed to parse data record at line %,d in file '%s': %s\nLine is: %s", lineNumber,
                                                         file, ex, lineContent);
                        LOG.error(msg, ex);

                        continue;
                    }

                    // set general fields
                    data.setAgentName(agentName);
                    data.setTransactionName(testCaseName);
                    
                    final char typeCode = byteRow.charAt(0, 0);
                    final long time = data.getTime();
                    
                    switch (typeCode)
                    {
                        case 'T':
                            if (data instanceof TransactionData)
                            {
                                final TransactionData td = (TransactionData) data;
                                td.setTestUserNumber(userNumber);
                                td.getName().hashCode();
                                postProcessedData.addTransaction(td);
                            }
                            else
                            {
                                data.getName().hashCode();
                                postProcessedData.addOtherData(data);
                            }
                            break;
                        case 'A':
                            if (data instanceof ActionData)
                            {
                                final ActionData ad = (ActionData) data;
                                if (collectActionNames)
                                {
                                    chunk.getActionNames().put(time, ad.getName());
                                }
                                ad.getName().hashCode();
                                postProcessedData.addAction(ad);
                            }
                            else
                            {
                                data.getName().hashCode();
                                postProcessedData.addOtherData(data);
                            }
                            break;
                        case 'R':
                            if (data instanceof RequestData)
                            {
                                final RequestData rd = (RequestData) data;
                                if (adjustTimerName)
                                {
                                    final Entry<Long, String> entry = chunk.getActionNames().floorEntry(time);
                                    final String actionName = (entry != null) ? entry.getValue() : "UnknownAction";
                                    final Matcher m = WD_TIMER_NAME_PATTERN.matcher(rd.getName());
                                    rd.setName(m.replaceFirst(actionName));
                                }
                                final RequestData result = requestProcessing.postprocess(rd);
                                if (result != null)
                                {
                                    postProcessedData.addRequest(result);
                                }
                            }
                            else
                            {
                                data.getName().hashCode();
                                postProcessedData.addOtherData(data);
                            }
                            break;
                        case 'E':
                            if (data instanceof EventData)
                            {
                                final EventData ed = (EventData) data;
                                ed.getName().hashCode();
                                postProcessedData.addEvent(ed);
                            }
                            else
                            {
                                data.getName().hashCode();
                                postProcessedData.addOtherData(data);
                            }
                            break;
                        case 'P':
                            if (data instanceof PageLoadTimingData)
                            {
                                final PageLoadTimingData pd = (PageLoadTimingData) data;
                                if (adjustTimerName)
                                {
                                    final Entry<Long, String> entry = chunk.getActionNames().floorEntry(time);
                                    final String actionName = (entry != null) ? entry.getValue() : "UnknownAction";
                                    final Matcher m = WD_TIMER_NAME_PATTERN.matcher(pd.getName());
                                    pd.setName(m.replaceFirst(actionName));
                                }
                                pd.getName().hashCode();
                                postProcessedData.addPageLoadTiming(pd);
                            }
                            else
                            {
                                data.getName().hashCode();
                                postProcessedData.addOtherData(data);
                            }
                            break;
                        case 'W':
                            if (data instanceof WebVitalData)
                            {
                                final WebVitalData wd = (WebVitalData) data;
                                wd.getName().hashCode();
                                postProcessedData.addWebVital(wd);
                            }
                            else
                            {
                                data.getName().hashCode();
                                postProcessedData.addOtherData(data);
                            }
                            break;
                        case 'V':
                            if (data instanceof CustomValue)
                            {
                                final CustomValue cv = (CustomValue) data;
                                cv.getName().hashCode();
                                postProcessedData.addCustomValue(cv);
                            }
                            else
                            {
                                data.getName().hashCode();
                                postProcessedData.addOtherData(data);
                            }
                            break;
                        case 'C':
                            if (data instanceof CustomData)
                            {
                                final CustomData cd = (CustomData) data;
                                cd.getName().hashCode();
                                postProcessedData.addCustomTimer(cd);
                            }
                            else
                            {
                                data.getName().hashCode();
                                postProcessedData.addOtherData(data);
                            }
                            break;
                        case 'J':
                            if (data instanceof JvmResourceUsageData)
                            {
                                final JvmResourceUsageData jd = (JvmResourceUsageData) data;
                                jd.getName().hashCode();
                                postProcessedData.addJvmResourceUsage(jd);
                            }
                            else
                            {
                                data.getName().hashCode();
                                postProcessedData.addOtherData(data);
                            }
                            break;
                        default:
                            data.getName().hashCode();
                            if (data instanceof TransactionData) { postProcessedData.addTransaction((TransactionData) data); }
                            else if (data instanceof ActionData) { postProcessedData.addAction((ActionData) data); }
                            else if (data instanceof RequestData) { postProcessedData.addRequest((RequestData) data); }
                            else if (data instanceof EventData) { postProcessedData.addEvent((EventData) data); }
                            else if (data instanceof PageLoadTimingData) { postProcessedData.addPageLoadTiming((PageLoadTimingData) data); }
                            else if (data instanceof WebVitalData) { postProcessedData.addWebVital((WebVitalData) data); }
                            else if (data instanceof CustomValue) { postProcessedData.addCustomValue((CustomValue) data); }
                            else if (data instanceof CustomData) { postProcessedData.addCustomTimer((CustomData) data); }
                            else if (data instanceof JvmResourceUsageData) { postProcessedData.addJvmResourceUsage((JvmResourceUsageData) data); }
                            else { postProcessedData.addOtherData(data); }
                            break;
                    }
                    
                    lineNumber++;
                }

                // deliver the chunk of parsed data records

                dispatcher.addPostprocessedData(postProcessedData);
            }
            catch (final InterruptedException e)
            {
                break;
            }
        }
    }
}
